<<<<<<< HEAD:pillar/cluster/services.sls
# This file regroups services names. It's purpose is to help allowing multiple Linux distros in the future (like debian, etc)
services:
  apache: httpd
  dns: named
  dhcp: dhcpd
  sftp: vsftpd
  firewalld: firewalld
  xinetd: xinetd
  ntp: ntpd
  ldapserver: slapd
  webserver: httpd
  salt_minion: salt-minion
  tftpserver: tftp
  munge: munge
  slurmserver: slurmctld
  slurmclient: slurmd
  rpcbind: rpcbind
  nfs_server: nfs-server
  sssd: sssd
  nscd: nscd
  networkmanager: NetworkManager
  shinken_arbiter: shinken-arbiter
  shinken_broker: shinken-broker
  shinken_poller: shinken-poller
  shinken_reactionner: shinken-reactionner
  shinken_receiver: shinken-receiver
  shinken_scheduler: shinken-scheduler
  mongodb_server: mongod
  nrpe: nrpe
=======
# This file regroups services names. It's purpose is to help allowing multiple Linux distros in the future (like debian, etc)
services:
  apache: httpd
  dns: named
  dhcp: dhcpd
  sftp: vsftpd
  firewalld: firewalld
  xinetd: xinetd
  ntp: ntpd
  ldapserver: slapd
  webserver: httpd
  salt_minion: salt-minion
  tftpserver: tftp
  munge: munge
  slurmserver: slurmctld
  slurmclient: slurmd
  rpcbind: rpcbind
  nfs_server: nfs-server
  sssd: sssd
  nscd: nscd
  networkmanager: NetworkManager
  shinken_arbiter: shinken-arbiter
  shinken_broker: shinken-broker
  shinken_poller: shinken-poller
  shinken_reactionner: shinken-reactionner
  shinken_receiver: shinken-receiver
  shinken_scheduler: shinken-scheduler
  mongodb_server: mongod
>>>>>>> fd940a25f1140ac17f02364496b45f25fb24a45f:pillar/services.sls
